services:
  weather_bot_app:
    build:
      context: .
      dockerfile: Weather_Bot/Dockerfile
    container_name: weather_bot_app
    restart: always
    volumes:
      - ./.env:/app/.env
   
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTIONS=1
      - DOTNET_PRINT_TELEMETRY_MESSAGE=false
      - TZ=Europe/Warsaw
      - BotConfiguration__TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BotConfiguration__TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - BotConfiguration__LATITUDE=${LATITUDE}
      - BotConfiguration__LONGITUDE=${LONGITUDE}
      - BotConfiguration__WINDY_API_KEY=${WINDY_API_KEY}
      - BotConfiguration__LUBLIN_LATITUDE=${LATITUDE_LUBLIN}
      - BotConfiguration__LUBLIN_LONGITUDE=${LONGITUDE_LUBLIN}
      - BotConfiguration__NEMO_POINT_LATITUDE=${NEMO_POINT_LATITUDE}
      - BotConfiguration__NEMO_POINT_LONGITUDE=${NEMO_POINT_LONGITUDE}